version: '3'

networks:
  shared_lan:
    name: nms-internal-lan
    external: true

services:
  opennms:
    # Build the image from the Dockerfile in the current folder
    build: 
      context: .
      dockerfile: Dockerfile
    
    container_name: opennms-container
    hostname: opennms-host
    env_file:
      - .env

    # CONNECT TO NETWORK
    networks:
      - shared_lan

    ports:
      - "8980:8980"
      - "8101:8101"
      - "162:1162/udp"
    
    volumes:
      - opennms-data:/opt/opennms/share:z
      - opennms-etc:/opt/opennms/etc:z

volumes:
  opennms-data:
  opennms-etc: